App_stor/urls.py
from .views import product_list,product_detail
from django.urls import path
app_name = 'App_stor'
urlpatterns = [
    path("", product_list,name="product_list"),
    path('<slug:category_slug>/', product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail,name='product_detail'),

]

My_stor/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('cart/', include('cart.urls')),
    path("", include("App_stor.urls",namespace='App_stor')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('user/', include('user.urls', namespace='user')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
 path('', views.cart_detail, name='cart_detail'),
 path('add/<int:product_id>/', views.cart_add, name='cart_add'),
 path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
 
    
]

App_stor/models.py
from django.db import models
from django.urls import reverse
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    def get_url(self):
        return reverse('App_stor:product_list_by_category',args=[self.slug])

    

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('App_stor:product_detail',args=[self.id, self.slug])
    
        

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

App_stor/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator,EmptyPage
from django.db.models import Q


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = None
    products_count = 0
    
    query = request.GET.get('query')
    if query:
        products = Product.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(category__name__icontains=query)
        ).distinct()
        products_count = products.count()
    else:
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = Product.objects.filter(category=category, available=True)
            products_count = products.count()
        else:
            products = Product.objects.filter(available=True)
            products_count = products.count()

    p = Paginator(products,6)
    page_num = request.GET.get('page',1)
    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)
    return render(request,'store/store.html',
                                {'category': category,
                                'categories': categories,
                                'products': page,
                                "products_count": products_count})

    
    
def product_detail(request, id, slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()

    return render(request,'store/product-detail.html',{'product': product,'cart_product_form': cart_product_form})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404,HttpResponseRedirect
from django.views.decorators.http import require_POST
from App_stor.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

App_stor/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{%block content%}



<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if cart|length == 0 %}
	<div class="container">
		<h2 class="text-center">Your cart is empty.</h2>
		<div class="card">
			<div class="card-body">
			<a href="{% url "App_stor:product_list" %}" class="btn btn-primary btn-block"> Continue Shopping </a>
			</div>
		</div>
		
	</div>
{%else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>



{% for item in cart %}
{% with product=item.product %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src= {{ product.image.url }} class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ product.get_absolute_url }}" class="title text-dark">>{{ product.name }}</a>
				{% comment %} <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p> {% endcomment %}
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
		<td class="text-right">
		<div class="col"> 
	 
				{% comment %} <var class="price">{{ item.quantity }} </var>  {% endcomment %}
				<form action="{% url "cart:cart_add" product.id %}" method="post">
					{{ item.update_quantity_form.quantity }}
					{{ item.update_quantity_form.override }}
					<span> 
					<input class="btn btn-success" type="submit" value="Update">

					</span>
					{% csrf_token %}
				</form>
		</div>
	</td> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">${{ item.total_price }}</var> 
			<small class="text-muted"> ${{ item.price }} each </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
		<form action="{% url "cart:cart_remove" product.id %}" 
		method="post">
		<input class="btn btn-danger" type="submit" value="Remove">
		{% csrf_token %}
 	</form>
	{% comment %} <a href="" class="btn btn-danger"> Remove</a> {% endcomment %}
	</td>
</tr>

{% endwith %}
{%endfor%}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{ cart.get_total_price }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> $00.00</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ cart.get_total_price }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src={% static "/images/misc/payments.png"  %} height="26">
			</p>
			<a href= "{% url "orders:order_create" %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url "App_stor:product_list" %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endif %}
{% endblock %}
</body>
</html>