App_stor/urls.py
from .views import product_list,product_detail
from django.urls import path
app_name = 'App_stor'
urlpatterns = [
    path("", product_list,name="product_list"),
    path('<slug:category_slug>/', product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail,name='product_detail'),

]

My_stor/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('cart/', include('cart.urls')),
    path("", include("App_stor.urls",namespace='App_stor')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('user/', include('user.urls', namespace='user')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
 path('', views.cart_detail, name='cart_detail'),
 path('add/<int:product_id>/', views.cart_add, name='cart_add'),
 path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

user/urls.py
from django.urls import path
from . import views
app_name = 'user'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('register/', views.register, name='register'),
]

App_stor/models.py
from django.db import models
from django.urls import reverse
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    def get_url(self):
        return reverse('App_stor:product_list_by_category',args=[self.slug])

    

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('App_stor:product_detail',args=[self.id, self.slug])
    
        

App_stor/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator,EmptyPage
from django.db.models import Q


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = None
    products_count = 0
    
    query = request.GET.get('query')
    if query:
        products = Product.objects.filter(
            Q(name__icontains=query) | 
            Q(description__icontains=query) |
            Q(category__name__icontains=query)
        ).distinct()
        products_count = products.count()
    else:
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = Product.objects.filter(category=category, available=True)
            products_count = products.count()
        else:
            products = Product.objects.filter(available=True)
            products_count = products.count()

    p = Paginator(products,6)
    page_num = request.GET.get('page',1)
    try:
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)
    return render(request,'store/store.html',
                                {'category': category,
                                'categories': categories,
                                'products': page,
                                "products_count": products_count})

    
    
def product_detail(request, id, slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()

    return render(request,'store/product-detail.html',{'product': product,'cart_product_form': cart_product_form})

App_stor/templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Django-Store</title>

<link href={% static "images/favicon.ico" %} rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src={% static 'js/jquery-2.0.0.min.js' %} type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src={ % static 'js/bootstrap.bundle.min.js'%} type="text/javascript"></script>
<link href={% static "css/bootstrap.css" %} rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href={ % static 'fonts/fontawesome/css/all.min.css'%} type="text/css" rel="stylesheet">

<!-- custom style -->
<link href={% static "css/ui.css" %} rel="stylesheet" type="text/css"/>
<link href={% static "css/responsive.css" %} rel="stylesheet" media="only screen and (max-width: 1200px)" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<!-- custom javascript -->
<script src={% static "js/script.js" %} type="text/javascript"></script>

<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>

	</script>
<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	$( function() {
		var availableTags = [
			"Shoes",
			"Laptops",
			"Hats",
			"Sunglasses",
			"T-shirts",
			"Backpacks",
			"Watches",
			"Dresses",
			"Headphones",
			"Jackets",
			"Perfumes",
			"Cameras",
			"Books",
			"Jewelry",
			"Handbags",
			"Socks",
			"Skincare products",
			"Pants",
			"Toys",
			"Stationery",
			"Makeup",
			"Swimwear",
			"Fitness equipment",
			"Water bottles",
			"Kitchen appliances",
			"Furniture",
			"Sports equipment",
			"Candles",
			"Art supplies",
			"Pet accessories",
			"Bedding",
			"Bath and body products",
			"Musical instruments",
			"Plants",
			"Cookware",
			"Board games",
			"Baby products",
			"Home decor",
			"Party supplies",
			"Office supplies",
			"Bicycles",
			"Cleaning products",
			"Garden tools",
			"Projectors",
			"Musical accessories",
			"Travel accessories",
			"Electronics",
			"Artwork",
			"Lighting fixtures",
			"Outdoor gear"
		];
		$( "#searchproducts" ).autocomplete({
		  source: availableTags
		});
	  } );

}); 
// jquery end
</script>

</head>
<body>


	<header class="section-header">
		<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
		<div class="container">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarTop4">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item dropdown">
					 <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">   Language </a>
					<ul class="dropdown-menu small">
						<li><a class="dropdown-item" href="#">English</a></li>
						<li><a class="dropdown-item" href="#">Arabic</a></li>
						<li><a class="dropdown-item" href="#">Russian </a></li>
					</ul>
				</li>
				<li class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> USD </a>
					<ul class="dropdown-menu small">
						<li><a class="dropdown-item" href="#">EUR</a></li>
						<li><a class="dropdown-item" href="#">AED</a></li>
						<li><a class="dropdown-item" href="#">RUBL </a></li>
					</ul>
				</li>
			</ul>
			<ul class="navbar-nav">
				<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
				<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
			</ul> <!-- list-inline //  -->
		  </div> <!-- navbar-collapse .// -->
		</div> <!-- container //  -->
		</nav>
		
		<section class="header-main border-bottom">
			<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-2 col-md-3 col-6">
				<a href="{% url "App_stor:product_list" %}" class="brand-wrap">
					<img class="logo" src={% static "./images/logo.jpg" %}>
				</a> <!-- brand-wrap.// -->
			</div>
			<div class="col-lg col-sm col-md col-6 flex-grow-0">
				<div class="category-wrap dropdown d-inline-block float-right">
				</div>  <!-- category-wrap.// -->
			</div> <!-- col.// -->
			<a href="{% url "App_stor:product_list" %}" class="btn btn-outline-primary">Store</a>
			<div class="col-lg  col-md-6 col-sm-12 col">
				<form action="#" class="search">
					<div class="input-group w-100">
						<input type="text" class="form-control" name="query" style="width:60%;" id="searchproducts" placeholder="Search">
						
						<div class="input-group-append">
						  <button class="btn btn-primary" type="submit">
							<i class="fa fa-search"></i>
						  </button>
						</div>
					</div>
				</form> <!-- search-wrap .end// -->
			</div> <!-- col.// -->
			<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
						<div class="d-flex justify-content-end mb-3 mb-lg-0">
							<div class="widget-header">
								<small class="title text-muted">Welcome guest!</small>
								<div> 
									<a href="{% url "user:signin" %}">Sign in</a> <span class="dark-transp"> | </span>
									<a href="{% url "user:register" %}"> Register</a>
								</div>
							</div>
							<a href="{% url "cart:cart_detail" %}" class="widget-header pl-3 ml-3">
								<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
								<span class="badge badge-pill badge-danger notify">{{ cart|length }}</span>
							</a>
						</div> <!-- widgets-wrap.// -->
					</div> <!-- col.// -->
		</div> <!-- row.// -->
			</div> <!-- container.// -->
	</section> <!-- header-main .// -->
		


</header> <!-- section-header.// -->
{%block content %}

{% endblock %}